### PR TITLE
fix your lying

### PR DESCRIPTION
**Pull request by Klathmon**
By moving one variable back to where it was, the performance of the JS code stays almost exactly the same.

### CODE REVIEW

**Comment by alexhultman** [comment]
This PR is not even compiling and even if it still works in JS you have broken the mathematical algorithm.

You are missing the point. The point is to show that the "optimized" C++ Google used in their video actually is very far from being optimized at all, and that the V8 environment simply cannot efficiently follow code that is more complex than one single for loop with no unrollings.

**Comment by Klathmon** [comment]
Yeah, i know. In my haste i misread `j` for `i` and royally messed it up. I pulled the PR, and i left my comments on reddit.

**Comment by alexhultman** [comment]
I have updated the conclusion. Maybe you are interested in taking a look.

**Comment by Klathmon** [comment]
I agree with the changes, but I can't say I've seen anyone trying to say those things. It seems like you are building yourself a nice strawman to kick down here.

You could help memakean ass of myself a second time by providing sources where you have read these things!

Writing perf critical code in JS is almost universally regarded as a bad idea, almost always the "solution" is to write that code in another language where possible and call it from JS if you want the ease of use of JS.

And while some people want to do the things you said (stuff like write kernel code in JS) its almost always to make a piece that's not performance critical easier to maintain.

**Comment by alexhultman** [comment]
https://medium.com/@ghaiklor/how-v8-optimises-javascript-code-a0f3bbd46ac9#.krzzzsoqx

"I suppose, some of you heard that JavaScript executes as fast as C++. Some of you don’t understand how it’s even possible."

This would be one of the **many, many, many, many, many** JavaScript fanatics that makes claims like these.

**Comment by Klathmon** [comment]
I agree that's a piss poor opening paragraph. I guess I just don't see it that much.

Still, my response is that there are idiots in every language...

**Pull request closed without merging**
